version: '3'
services:
  backend:
    build: ./rides_app 
    ports:
      - "8080:8080" 
    env_file:
      - .env 


#  frontend:
#    build: ./frontend  # Caminho para a pasta do frontend
#    ports:
#      - "80:80"  # Expõe a porta 80 do frontend
    depends_on:
      - backend  # Garante que o backend seja iniciado antes do frontend
